Raymax/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Raymax.Data;
using Raymax.Models;
using Raymax.Models.ViewModels;

namespace Raymax.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly ApplicationDbContext _db;
        public InvoiceController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var List = await _db.Invoices.Include(a => a.Products).ToListAsync();
            return View(List);
        }

        //create get
        public IActionResult Create()
        {
            return View();
        }

        //CreatePost
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Invoice invoice)
        {
            _db.Invoices.Add(invoice);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        //edit get
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var EditID = await _db.Invoices.Include(m => m.Products).FirstOrDefaultAsync(m => m.ID == id);

            if (EditID == null)
            {
                return NotFound();
            }

            EditInvoiceViewModel model = new EditInvoiceViewModel()
            {
                Invoice = EditID
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditInvoiceViewModel EIVM)
        {
            if (ModelState.IsValid)
            {
                var subCatFromDb = await _db.Invoices.Include(m => m.Products).FirstOrDefaultAsync(m => m.ID == id);
                subCatFromDb.CustomerName = EIVM.Invoice.CustomerName;
                subCatFromDb.Address = EIVM.Invoice.Address;
                subCatFromDb.Contact = EIVM.Invoice.Contact;
                subCatFromDb.Date_Created = EIVM.Invoice.Date_Created;
                
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            EditInvoiceViewModel modelVM = new EditInvoiceViewModel()
            {
                Invoice = EIVM.Invoice
            };
            return View(modelVM);
        }



        #region API CALL
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new
            {
                data = await _db.Invoices.Include(a => a.Products).ToListAsync()
            });
        }

        [HttpDelete]
        public IActionResult DeleteInvoice(int id)
        {
            var objFromDb = _db.Invoices.SingleOrDefault(a => a.ID == id);
            if (objFromDb == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Error while deleting."
                });
            }

            _db.Invoices.Remove(objFromDb);
            _db.SaveChanges();
            return Json(new
            {
                success = true,
                message = "Deleted Successfully."
            });

        }
        #endregion

        public IActionResult Print(int? id)
        {
            PrintViewModel model = new PrintViewModel()
            {
                Invoice = _db.Invoices.Include(a => a.Products).FirstOrDefault(a => a.ID == id),
                Terms = _db.Terms.ToList(),
            };

            return View(model);
        }

    }
}

Raymax/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Raymax.Data;
using Raymax.Models;

namespace Raymax.Controllers
{
    [Authorize]
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShopController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Shop
        public async Task<IActionResult> Index()
        {
            return View(await _context.Terms.ToListAsync());
        }

        // GET: Shop/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terms = await _context.Terms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (terms == null)
            {
                return NotFound();
            }

            return View(terms);
        }

        // GET: Shop/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shop/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,TermsANDPolicy")] Terms terms)
        {
            if (ModelState.IsValid)
            {
                _context.Add(terms);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(terms);
        }

        // GET: Shop/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terms = await _context.Terms.FindAsync(id);
            if (terms == null)
            {
                return NotFound();
            }
            return View(terms);
        }

        // POST: Shop/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,TermsANDPolicy")] Terms terms)
        {
            if (id != terms.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(terms);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TermsExists(terms.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(terms);
        }

        // GET: Shop/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terms = await _context.Terms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (terms == null)
            {
                return NotFound();
            }

            return View(terms);
        }

        // POST: Shop/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var terms = await _context.Terms.FindAsync(id);
            _context.Terms.Remove(terms);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TermsExists(int id)
        {
            return _context.Terms.Any(e => e.ID == id);
        }
    }
}

Raymax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Raymax</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.css" />
    <link href="~/lib/bootstrap/dist/css/fontawesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav style="padding: .5rem 1rem;font: 14px/1.4 Georgia, serif;" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" >Raymax</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Invoice" asp-action="Index">Invoice History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Invoice" asp-action="Create">New Invoice</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Shop" asp-action="Index">Terms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Administration" asp-action="Index">User List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2020 - Raymax - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/fontawesome.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

    <script src="~/js/invoice.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://use.fontawesome.com/9041f4fa60.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Raymax/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Raymax</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/lib/bootstrap/dist/css/fontawesome.css" rel="stylesheet" />
</head>
<body>
    <header>
                    

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/fontawesome.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp"></script>

    <script src="~/js/invoice.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://use.fontawesome.com/9041f4fa60.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Raymax/Views/Shared/_TermsAndCondition.cshtml
@model IEnumerable<Raymax.Models.Terms>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TermsANDPolicy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TermsANDPolicy)
                </td>
            </tr>
        }
    </tbody>
</table>